var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<e.length-1;h++){var f=e[h];if(!(f in d))return;d=d[f]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(h){return this.context_.yieldAllIterator_=null,this.context_.throw_(h),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var didv4=document.querySelector("main .zvxcoin .one4 .switch label"),didv41=document.querySelector("main .zvxcoin .one4 .switch label input"),didv6=document.querySelector("main .zvxcoin .one6 .switch label"),didv61=document.querySelector("main .zvxcoin .one6 .switch label input"),didv8=document.querySelector("main .zvxcoin .one8 .switch label"),didv81=document.querySelector("main .zvxcoin .one8 .switch label input"),one5=document.querySelector("main .zvxcoin .one5");one5.classList.add("displaynone");
var one7=document.querySelector("main .zvxcoin .one7");one7.classList.add("displaynone");var one9=document.querySelector("main .zvxcoin .one9");one9.classList.add("displaynone");var eth="1",ethce=document.querySelector("main .choose .dropdown .bbb"),demm=document.querySelector("main .choose .dropdown .dropbtn1 li"),erc20=document.querySelector("main .erc20"),zvxcoin=document.querySelector("main .zvxcoin");erc20.classList.add("displaynone");
didv4.oninput=function(){didv41.checked?one5.classList.remove("displaynone"):one5.classList.add("displaynone")};didv6.oninput=function(){didv61.checked?one7.classList.remove("displaynone"):one7.classList.add("displaynone")};didv8.oninput=function(){didv81.checked?one9.classList.remove("displaynone"):one9.classList.add("displaynone")};
ethce.onclick=function(){var a=document.querySelector("main .choose .dropdown .bbb li");switch(a.value){case 1:erc20.classList.remove("displaynone");zvxcoin.classList.add("displaynone");a.value=2;demm.value=1;eth=2;fb();break;case 2:zvxcoin.classList.remove("displaynone");erc20.classList.add("displaynone");a.value=1;demm.value=2;eth=1;fb();break;default:console.log("caonima")}};
var main1=document.querySelector("main .main1 .choose .dropdown .dropbtn h3"),main2=document.querySelector("main .main1 .choose .dropdown .dropbtn1 h3"),main3=document.querySelector("main .main1 .choose .dropdown .bbb h3"),main4=document.querySelector("main .erc20 .title h2"),main5=document.querySelector("main .erc20 .title h4"),main6=document.querySelector("main .erc20 .one .one1 .name "),main7=document.querySelector("main .erc20 .one .one1 .name1 "),main8=document.querySelector("main .erc20 .one .one2 .typpl "),
main9=document.querySelector("main .erc20 .one .one3 h5 "),main10=document.querySelector("main .erc20 .one .one4 button "),zvxhm=document.querySelector("main .zvxcoin .title h2"),zvxhm1=document.querySelector("main .zvxcoin .two .tltle1"),zvxhm2=document.querySelector("main .zvxcoin .two .one1 .name1"),zvxhm3=document.querySelector("main .zvxcoin .two .one1 .name2"),zvxhm4=document.querySelector("main .zvxcoin .two .one2 .name4"),zvxhm5=document.querySelector("main .zvxcoin .two .one3 .name5"),zvxhm6=
document.querySelector("main .zvxcoin .two .one4 .name6"),zvxhm7=document.querySelector("main .zvxcoin .two .one5 .name7"),zvxhm8=document.querySelector("main .zvxcoin .two .buy1 .name8"),zvxhm9=document.querySelector("main .zvxcoin .two .buy1 .name9"),zvxhm10=document.querySelector("main .zvxcoin .two .buy2 .name10"),zvxhm11=document.querySelector("main .zvxcoin .two .buy2 .name11"),zvxhm12=document.querySelector("main .zvxcoin .two .sell1 .name12"),zvxhm13=document.querySelector("main .zvxcoin .two .sell1 .name13"),
zvxhm14=document.querySelector("main .zvxcoin .two .sell2 .name14"),zvxhm15=document.querySelector("main .zvxcoin .two .sell2 .name15"),zvxhm16=document.querySelector("main .zvxcoin .two .set1 .name16"),zvxhm17=document.querySelector("main .zvxcoin .two .set2 .name17"),zvxhm18=document.querySelector("main .zvxcoin .two .set3 .name18"),zvxhm19=document.querySelector("main .zvxcoin .two .set4 .name19"),zvxhm20=document.querySelector("main .zvxcoin .two .one6 .name20"),zvxhm21=document.querySelector("main .zvxcoin .two .one7 .name21"),
zvxhm22=document.querySelector("main .zvxcoin .two .limit .name22"),zvxhm23=document.querySelector("main .zvxcoin .two .limit .name23"),zvxhm24=document.querySelector("main .zvxcoin .two .limit .name24"),zvxhm25=document.querySelector("main .zvxcoin .two .one8 .name25"),zvxhm26=document.querySelector("main .zvxcoin .two .one9 .name26"),zvxhm27=document.querySelector("main .zvxcoin .two .promote .name27"),zvxhm28=document.querySelector("main .zvxcoin .two .promote .name28"),zvxhm29=document.querySelector("main .zvxcoin .two .promote .name29"),
zvxhm30=document.querySelector("main .zvxcoin .two .one10 h4"),zvxhm31=document.querySelector("main .zvxcoin .two .one11 "),zvxhm32=document.querySelector("main .zvxcoin .two .one12 ");
function fb(){main1.textContent=mint[2];switch(parseInt(eth)){case 1:main2.textContent=mint[0];main3.textContent=mint[1];zvxhm.textContent=cczvx[0];zvxhm1.textContent=cczvx[1];for(var a=2;6>a;a++)eval("zvxhm"+[a]).setAttribute("placeholder",cczvx[a]);zvxhm6.textContent=cczvx[6];zvxhm7.textContent=cczvx[7];for(a=8;20>a;a++)eval("zvxhm"+[a]).setAttribute("placeholder",cczvx[a]);zvxhm20.textContent=cczvx[20];zvxhm21.textContent=cczvx[21];for(a=22;25>a;a++)eval("zvxhm"+[a]).setAttribute("placeholder",
cczvx[a]);zvxhm25.textContent=cczvx[25];zvxhm26.textContent=cczvx[26];for(a=27;30>a;a++)eval("zvxhm"+[a]).setAttribute("placeholder",cczvx[a]);zvxhm30.textContent=cczvx[30];zvxhm31.textContent=cczvx[31];zvxhm32.textContent=cczvx[32];break;case 2:main2.textContent=mint[1];main3.textContent=mint[0];main4.textContent=erc201[0];main5.textContent=erc201[1];main6.setAttribute("placeholder",erc201[2]);main7.setAttribute("placeholder",erc201[3]);main8.setAttribute("placeholder",erc201[4]);main9.textContent=
erc201[5];main10.textContent=erc201[6];break;default:console.log("erro")}}fb();var zvxbutton=document.querySelector("main .main2 .zvxcoin .two .one12"),erc20buttn=document.getElementById("erc20buttn");zvxbutton.addEventListener("click",validation);erc20buttn.addEventListener("click",erc20tion);var amount_9="0";document.getElementById("amount_9").oninput=function(){amount_9=document.getElementById("amount_91").checked?"3":"0"};
function validation(){var a=document.getElementById("zvxname").value.length,b=document.getElementById("symbol").value.length,c=document.getElementById("supply").value.length;if(0===Accounts.length)return tanyixia(hint[0],hint[1]),!1;if(0===a)tanyixia(hint[0],hint[13]);else if(56!=chainId)tanyixia(hint[0],hint[2]);else{if(0===b)return tanyixia(hint[0],hint[3]),!1;if(0===c)return tanyixia(hint[0],hint[4]),!1;mnnnzvx()}}
function mnnnzvx(){var a=new ethers.Contract(zvxbalance,VOTE_ZVXABI,window.getWeb3Provider().getSigner()),b=document.getElementById("zvxname").value,c=document.getElementById("symbol").value,d=document.getElementById("supply").value,e=document.getElementById("addrs_4").value;""===e&&(e=Accounts);var h={buyfee1:document.getElementById("buyfee1").value,buyfee2:document.getElementById("buyfee2").value,buyfee3:document.getElementById("buyfee3").value,buyfee4:document.getElementById("buyfee4").value};
h=[h.buyfee1,h.buyfee2,h.buyfee3,h.buyfee4];for(var f=0;4>f;f++)""===h[f]&&(h[f]="0");var k={buyfee1:document.getElementById("getfee1").value,buyfee2:document.getElementById("getfee2").value,buyfee3:document.getElementById("getfee3").value,buyfee4:document.getElementById("getfee4").value};k=[k.buyfee1,k.buyfee2,k.buyfee3,k.buyfee4];for(f=0;4>f;f++)""===k[f]&&(k[f]="0");f=document.getElementById("addrs_1").value;""===f&&(f="0x0000000000000000000000000000000000000000");var m=document.getElementById("addrs_2").value;
""===m&&(m=Accounts);var g=document.getElementById("addrs_5").value;""===g&&(g=Accounts);var p=[f,m,zvxser,e,g,zvxuni];e=document.getElementById("amount_1").value;""===e&&(e="0");f=document.getElementById("amount_2").value;""===f&&(f="0");m=document.getElementById("amount_3").value;""===m&&(m="0");g=document.getElementById("amount_4").value;""===g&&(g="0");var B=document.getElementById("amount_5").options[document.getElementById("amount_5").selectedIndex].value,v=document.getElementById("amount_6").value;
""===v&&(v="0");var w=document.getElementById("amount_7").value;""===w&&(w="0");var x=document.getElementById("amount_8").value;""===x&&(x="0");var C=[e,f,m,g,B,v,w,x,amount_9];(function(){var z,y,n,A,q,r,t;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){switch(l.nextAddress){case 1:return l.setCatchFinallyBlocks(2),z=function(){r===A?setTimeout(y,2E3):tanyixia(hint[9],hint[10]+n[r-1])},y=function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(u){if(1==u.nextAddress)return u.yield(a.getListByOwner(Accounts),
2);n=u.yieldResult;r=n.length;z();u.jumpToEnd()})},l.yield(a.getListByOwner(Accounts),4);case 4:return n=l.yieldResult,A=n.length,tanyixia(hint[0],hint[5]),l.yield(a.serviceFee(),5);case 5:return q=l.yieldResult,q=(q/1E18).toFixed(2),tanyixia(hint[0],hint[6]),l.yield(a.createChild(b,c,d,h,k,p,C,promoter,{value:ethers.utils.parseEther(q)}),6);case 6:return tanyixia(hint[7],hint[8]),l.yield(a.getListByOwner(Accounts),7);case 7:return n=l.yieldResult,r=n.length,l.yield(y(),8);case 8:l.leaveTryBlock(0);
break;case 2:t=l.enterCatchBlock(),console.log(t),tanyixia(hint[11],hint[12]+t.code+":"+t.message),l.jumpToEnd()}})})()}var tanchuang=document.getElementById("tanchuang");tanchuang.onclick=function(){document.querySelector("body .bgbt").classList.toggle("dispnone")};function tanyixia(a,b){var c=document.querySelector("body .bgbt");document.getElementById("tanchuang").textContent=hint[15];c.classList.remove("dispnone");gengxintanchuang(a,b)}
function gengxintanchuang(a,b){document.querySelector("body .tan .title h3").textContent=a;document.querySelector("body .tan .title1 h4").textContent=b}function getWeb3Provider(){if(!window.web3Provider){if(!window.ethereum)return console.error("there is no web3 provider."),null;window.web3Provider=new ethers.providers.Web3Provider(window.ethereum,"any")}return window.web3Provider}
function erc20tion(){var a=document.getElementById("erc20name").value.length,b=document.getElementById("rec20symbol").value.length,c=document.getElementById("erc20supply").value.length;if(0===Accounts.length)return tanyixia(hint[0],hint[1]),!1;if(0===a)tanyixia(hint[0],hint[13]);else{if(0===b)return tanyixia(hint[0],hint[3]),!1;if(0===c)return tanyixia(hint[0],hint[4]),!1;switch(chainId){case 56:minterc20();break;case 66:minterc20();break;case 128:minterc20();break;case 137:minterc20();break;default:tanyixia(hint[0],
hint[14])}}}
function minterc20(){contract=new ethers.Contract(erc20balance,zvx_ABI,window.getWeb3Provider().getSigner());var a=document.getElementById("erc20name").value,b=document.getElementById("rec20symbol").value,c=document.getElementById("erc20supply").value;(function(){var d,e,h,f,k,m;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:return g.setCatchFinallyBlocks(2),d=function(){h===k?setTimeout(e,2E3):tanyixia(hint[9],hint[10]+k)},e=function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){if(1==p.nextAddress)return p.yield(contract.get(Accounts),
2);k=p.yieldResult;d();p.jumpToEnd()})},g.yield(contract.get(Accounts),4);case 4:return h=g.yieldResult,tanyixia(hint[0],hint[5]),g.yield(contract.serviceFee(),5);case 5:return f=g.yieldResult,f=(f/1E18).toFixed(2),tanyixia(hint[0],hint[6]),g.yield(contract.createChild(a,b,c,promoter,{value:ethers.utils.parseEther(f)}),6);case 6:return tanyixia(hint[7],hint[8]),g.yield(contract.get(Accounts),7);case 7:return k=g.yieldResult,g.yield(e(),8);case 8:g.leaveTryBlock(0);break;case 2:m=g.enterCatchBlock(),
console.log(m),tanyixia(hint[11],hint[12]+m.code+":"+m.message),g.jumpToEnd()}})})()};